language: cpp
dist: trusty

install:
  - pip install conan
  - conan user

matrix:
  include:
    - os: linux
      env: GCC_VER=4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    - os: linux
      env: GCC_VER=5.4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5.4

script:
  - export CXX=g++-$GCC_VER
  - conan install -s compiler=gcc -s compiler.version=$GCC_VER .
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
