language: cpp
dist: trusty

matrix:
  include:
    - gcc: "4.9"
      env: [CXX=g++-4.9, COMPILER=g++-4.9]
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
    - gcc: "4.8"
      env: [CXX=g++-4.8, COMPILER=g++-4.8]
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
