os: linux
language: cpp
compiler:
    - gcc

notifications:
    recipients:
        - achernov@byterox.com
    email:
        on_success: change
        on_failure: always

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
