language: cpp
dist: trusty

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
    - compiler: gcc
      env: COMPILER=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
