language: cpp
dist: trusty

matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    - os: linux
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

script:
  - export CXX=$COMPILER
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
