language: cpp
dist: trusty

install:
  - pip install conan
  - conan user

matrix:
  include:
    - os: linux
      env: [COMPILER=g++-4.8, COMPILER_VERSION=4.8]
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    - os: linux
      env: [COMPILER=g++-4.9, COMPILER_VERSION=4.9]
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

script:
  - export CXX=$COMPILER
  - conan install -s compiler=gcc -s compiler.version=$COMPILER_VERSION .
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
