language: cpp
dist: trusty

matrix:
  include:
    - compiler: g++-4.9
      env: CXX=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      script:
        - export CXX=g++-4.9
        - export CC=gcc-4.9
        - mkdir build && cd build
        - cmake ..
        - cmake --build .

    - compiler: g++-4.8
      env: CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      script:
        - export CXX=g++-4.9
        - export CC=gcc-4.9
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
