build:
platform:
#  - x64
  - x86

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: conan install -s compiler="%COMPILER%" -s compiler.version="%VER%"
  - mkdir build && cd build
  - cmake -G "%COMPILER% %VER% %PRODUCT%" ..
  - cmake --build . --config release

environment:
  matrix:
    - COMPILER: Visual Studio
      VER: 14
      PRODUCT: 2015
#    - TOOLCHAIN_VERSION: Visual Studio 12 2013
#    - TOOLCHAIN_VERSION: Visual Studio 11 2012
