build:
platform:
#  - x64
  - x86

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: conan install -s compiler.version=$VER
  - mkdir build && cd build
  - cmake -G "%TOOLCHAIN_VERSION%" ..
  - cmake --build . --config release

environment:
  matrix:
    - TOOLCHAIN_VERSION: Visual Studio 14 2015
      VER: 14
#    - TOOLCHAIN_VERSION: Visual Studio 12 2013
#    - TOOLCHAIN_VERSION: Visual Studio 11 2012
