version: 1.0.{build}
build:
platform:
#  - x64
  - x86

configuration:
#  - Debug
  - Release

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: conan install -s compiler="%COMPILER%" -s compiler.version="%VER%" -s arch="%PLATFORM%" -s build_type="%CONFIGURATION%"
  - mkdir build && cd build
  - cmake -G "%COMPILER% %VER% %PRODUCT%" ..
  - cmake --build . --config "%CONFIGURATION%"

environment:
  matrix:
    - COMPILER: Visual Studio
      VER: 14
      PRODUCT: 2015
    - COMPILER: Visual Studio
      VER: 10
      PRODUCT: 2010
